obj-$(CONFIG_DRM_PANEL_XIAOMI_RIVA_HX8394F) += panel-xiaomi-riva-hx8394f.o
obj-$(CONFIG_DRM_PANEL_XIAOMI_RIVA_ILI9881C) += panel-xiaomi-riva-ili9881c.o
obj-$(CONFIG_DRM_PANEL_XIAOMI_SANTONI_HX8394F) += panel-xiaomi-santoni-hx8394f.o
obj-$(CONFIG_DRM_PANEL_XIAOMI_UGGLITE_OTM1901A) += panel-xiaomi-ugglite-otm1901a.o
